services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./data_models:/app/data_models
      - ./optimization:/app/optimization
      - ./data:/data 
    networks:
      - hotel-ranking-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3838:3838"
    environment:
      - API_URL=http://backend:8001
    volumes:
      - ./data:/data 
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - hotel-ranking-network

networks:
  hotel-ranking-network:
    driver: bridge
